### ISSUE TITLE
Linear Overlay Navigation

### ISSUE THREAD

**Issue by fhgd** [pdfpc/pdfpc#102]
When I reached the last overlay,, normally my actual slide will be complete. Then I go ahead to the next slide and maybe want to go back to the last overlay of the last slide. This is not possible with pdfpc since I have to click again through all the overlays of the last slide. This would be not so good in a real presentation :-)

**Comment by rschroll** [comment]
I'm ... not sure why this is like this.  I guess it helps you move 
backwards through slides more quickly, but we already have the 
prevOverlay command for that.  And if we're only showing one slide out 
of an overlay, wouldn't it make more sense to show the last one, not 
the first?

Does anyone want to argue in favor of the current approach?

**Comment by cebe** [comment]
It helps when you have a presenter in the hand where you have only 2 buttons for next/prev.
Going back through the slides skipping all the overlays if you have a lot of them is really useful.

I see however why this may cause confusion and showing the last state of the overlay would make sense. But what if I press "back" again when I am on the last overlay? pdfpc has to remember the state of how it got here to have normal behavior when I came here from the last overlay and skip other overlays when I came from the next frame.

**Comment by fhgd** [comment]
Maybe a new command line switch could be introduced

    -n --navigation=[linear, first, last]    how to move forward and backward

with

    linear = one overlay is one slide (count pdf pages)
    first = go back to the first overlay of the last slide
    last = go back to the last overlay of the last slide

In my presentations I would prefer either 'linear' or 'last'.

**Comment by rschroll** [comment]
In general, I dislike options, since the complexity of a program grows 
faster than linearly with the number of options.  My preference would 
be for a new command, "backStrict" or "backLinear" or something, that 
would always move back one real slide, regardless of overlays.  Then 
you can set up your pdfpcrc file to use that instead of the default 
"back" command, or even bind a separate key to each.

As Carsten points out, going to the last slide of an overlay makes 
sense, but causes a lot of confusion about what should happen next.  We 
could try to store state to guess the right behavior, but this 
increases the complexity of the mental model the user needs to 
understand its behavior.  But this could also be made into a separate 
command, so people who want this behavior can access it.

**Comment by endzone** [comment]
On PDFPC 4.0.x, there seems to be a workaround to completely disable the slide / overlay grouping:

In $presentation.pdfpc, add

     [skip]

and nothing after it (i.e. if there is a line in this [skip] section listing the slides to skip, remove that line.
After that, start pdfpc and you will have no grouping at all.

**Comment by andybarry** [comment]
I think the new ````-g```` / ````--disable-auto-grouping```` option from #112 works pretty well for this because it is clear to the user what is going on and allows you to move back one overlay at a time.  I'm going to go ahead and close this, but reopen if the ````-g```` option isn't good enough for you.
