### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by sschuldenzucker** [pdfpc/pdfpc#106]
I started impressing collegues of mine by pdfpc's well-honed feature set (as it should be!) and they keep asking me about a version for Windows.
Has anyone made one? How hard would it be?

**Comment by AndreasBilke** [comment]
I never compiled it on windows but: cmake can generate visual studio project files, gtk+ is available on windows (and I think the other dependencies are also available). So, except from the movie playback support, it "should" work in theory.

**Comment by andybarry** [comment]
With #93, it's possible that compiling on Windows without movie support wouldn't require much coding at this point.  #74 has useful information for adding cross-platform movie support.

**Comment by cure-e-es** [comment]
Would just like to +1 getting a build happening for Windows (even without movie support would be just awesome). In my looking around, there is no software on windows what allows presenting PDFs in a presentation mode (except perhaps: pdfpresenter -- which unfortunately requires java).

I believe the interest would be significant in situations where installing Linux is not an option. Thanks for making a great bit of code!

**Comment by pseisam** [comment]
On windows you could also use cygwin for running pdfpc. A bit more effort to install, but works like a charm and is already available :)

**Comment by AndreasBilke** [comment]
Could you write some documentation for getting pdfpc with cygwin? This
would be nice to have.

**Comment by pseisam** [comment]
I just downloaded the tarball, extracted it and followed the installation instructions:

"mkdir build
cd build
cmake ..
make
make install"

It was pretty straight forward by fixing each error that occured after using "cmake .." with downloading the missing dependency with cygwins setup.exe. But to shorten this process down for you, this is what I remember:

Compile Runtime Dependencies:
- cmake
- automake
- make
- gcc
- gcc-c++
- libstdc++-4.8-dev

PDFPC Compile Dependencies (use the -dev packages):
- vala
- gtk
- gee
- libpoppler
- gstreamer
- libgstinterfaces1.0-devel (has gstreamer.audio included)

You also need x11 (I installed the whole category with cywins setup.exe) and start it seperatly with cygwin in order to be able to create windows.

If someone tries this, you should add what I missed in my description or ask questions if you encounter any problems.

**Comment by gspolly** [comment]
compiling works perfectly fine but running (obviously) requires the x-server. I am getting problems trying to run pdfpc from the cygwin console directly getting the error message:

```
Unable to init server: Could not connect to 127.0.0.1: Connection refused
(pdfpc:6244): Gtk-WARNING **: cannot open display:
```

starting from the terminal after opening an x window generally works but is cumbersome - and starts in the corresponding window...
Has anyone found a solution to this??

**Comment by sgraf812** [comment]
You probably need to `export DISPLAY=:0.0` or something. But then it will only open a single window, see https://github.com/pdfpc/pdfpc/issues/262
