### ISSUE TITLE
Add more timers on presenter's view

### ISSUE THREAD

**Issue by mhalano** [pdfpc/pdfpc#158]
LibreOffice Impress has a presentation mode which works in a very similar way to pdfpc. One difference is LibreOffice Impress shows two times: current time and past time. pdfpc just show one time (past time or current time). I think should be a good idea if exist flags to enable multiple times, like current time and remaining time. Some flags may be cancel each others (like past time and remaining time).

**Comment by nlgranger** [comment]
Here are some additional random suggestions, but I don't think I'd use that myself because it might prove distracting:
- A rehearsal mode to generate a timing file for each slide or section (and a diff-tool to compare two runs?)
- A slide-by-slide timer along with the global one.
- A shortcut to force start the global timer (presently it is triggered by switching to the second slide)

**Comment by fnevgeny** [comment]
>     * A shortcut to force start the global timer (presently it is triggered by switching to the second slide)

Press `s`...

**Comment by nlgranger** [comment]
I should read these man pages more carefully... thanks

**Comment by fnevgeny** [comment]
IMO, adding another ticking widget would be unnecessarily distracting. I'd instead suggest implementing a _run-time_ switching with a key shortcut (e.g., `Shift+t`) to cycle between the count up, count down, and clock (time of day) displays in the same place.
