### ISSUE TITLE
Too large windows in gnome 3.22 with Wayland and HiDPI

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#214]
On Gnome 3.22, Wayland and a HiDPI setting, the windows became too large, resulting in a huge overlapping.

The reason might be, that via the GTK API, we get the native screen resolution and GDK_SCALE of 2. We then created windows in native resolution which became scaled again from Wayland.

**Comment by perror** [comment]
I observe the exact same bug on my platform. But, I tried to understand what was going on.

First, I unset all the `GDK_` variables from my environment and the related variable from the `gconfig`. But, still the bug was here.

In fact, I think that the bug is coming from the fact that Xorg was not doing properly his job previously (forcing the developers to fill the gap with "_hacks_"). Previously, it was to the software to handle the change of DPI between the two screen and you had to apply a factor 2 (most of the time) between the two screens. Right now, Wayland seems to resize automatically this factor without any required manipulation from the software itself.

So, the bug we observe is just coming from the fact that `pdfpc` is applying a factor 2 zoom on the screen with another factor 2 zoom automatically applied by Wayland. The result is that the slides appears to be 2 times bigger than they should be.

Somehow, the previous hack should die in the long term (it is up to the graphical layer to handle these zoom factors according to the ratio between the screen, application developers shouldn't have to handle this). So, I guess that `pdfpc` should just detect that it is running under Xorg/Xfree/... and apply this factor, or just let the graphical layer to handle it.

What do you think ?

**Comment by AndreasBilke** [comment]
@perror Yes, exactly. It seems that this is going on. But I really don't like the idea of having a wayland and a separate Xorg code path.

**Comment by perror** [comment]
I understand... But, I think the opposite (in my humble opinion)... In fact, I think that a user application shouldn't have to set his own scale factor. It should be left to the graphical layer. So, I would have turned the default to be a "don't care about the scale factor" and add a few exceptions in case you are inside Xorg/Xfree and other exceptions. But, I may have missed your point.

**Comment by fnevgeny** [comment]
Perhaps pdfpc could try detecting whether it's running under Wayland and then skip the Xorg-specific workaround. E.g., by checking getenv of WAYLAND_DISPLAY. <https://stackoverflow.com/questions/45536141/how-i-can-find-out-if-a-linux-system-uses-wayland-or-x11>

**Comment by AndreasBilke** [comment]
We need the scaling for pixel perfect slide rendering. In X environments
(which is the majority I think) it works that way.

It also does not matter if Wayland or X is the exception. Depending on the
environment you have to behave differently.

**Comment by perror** [comment]
I can add that Debian unstable uses Wayland by default too, testing as well. And, soon the stable will be. Somehow, Wayland is spreading fast and will become the new standard.

**Comment by AndreasBilke** [comment]
I looked again in the GDK/GTK API. See https://developer.gnome.org/gdk3/stable/GdkScreen.html#gdk-screen-get-monitor-geometry . They clearly say that this size is in application pixels and there is a reference to scaling factors.

Lets say you have a monitor with 2000x1000 device pixels. Under X you get a geometry of 1000x500 pixel with scaling of 2. Under wayland, you get 2000x1000 with scaling of 2. So I think the GDK/GTK API is giving you wrong hints.

**Comment by rkraneis** [comment]
[Gnomes HiDpi HowTo](https://wiki.gnome.org/HowDoI/HiDpi) states 

> GTK+ makes hi-dpi work transparently in most places, 

and

> Similarly, Clutter tries to automatically handle the scaling factor on each drawing surface, 

So maybe there is something more going on?

**Comment by AndreasBilke** [comment]
> > Similarly, Clutter tries to automatically handle the scaling factor on each drawing surface, 
> 
> So maybe there is something more going on?

But Clutter is used on X session as well, right?

**Comment by phillipberndt** [comment]
Don't put too much faith in GTK's documentation. Their Wayland and HighDPI
support were quite buggy the last time I tried to make this work. It's
better to take actual behavior as a reference, and to expect that that
behavior will change in an upcoming version, especially if it differs from
the documentation.

**Comment by AndreasBilke** [comment]
Okay I did a PR to work around this wayland problem. In my test environment it works now. What about you @perror ?

**Comment by diraimondo** [comment]
I tested the PR in my setting and it looks to work under Wayland and using Gnome 3.26.1.

**Comment by perror** [comment]
I also confirm it fixed the problem (sorry for the delay!).

**Comment by diraimondo** [comment]
I don't know if it is related to this fix, but I'm facing a scaling problem using this workaround during my classes: the presenter screen proposes a too small previews. The main screen has proper dimensions. 

![schermata da 2017-11-08 10-33-08](https://user-images.githubusercontent.com/4376789/32541667-acd537c8-c470-11e7-9687-e3df7a09e116.png)

```
$ xrandr
Screen 0: minimum 320 x 200, current 4480 x 1800, maximum 8192 x 8192
XWAYLAND3 connected 3200x1800+0+0 (normal left inverted right x axis y axis) 290mm x 170mm
   3200x1800     59.96*+
XWAYLAND4 connected 1280x1024+3200+0 (normal left inverted right x axis y axis) 340mm x 270mm
   1280x1024     59.89*+
```

**Comment by AndreasBilke** [comment]
@diraimondo Could you open a new issue (with all the relevant informations about your environment)?
