### ISSUE TITLE
last_minutes is not respected in the .pdfpc file.

### ISSUE THREAD

**Issue by Drup** [pdfpc/pdfpc#218]
If `-l 5` is given on the command line, a section `last_minute` is added in the `.pdfpc` file, but this is not respected (and then removed) the next time `pdfpc` is launched without the option.

**Comment by AndreasBilke** [comment]
5 minutes is the default for `-l` so we drop this value for writing it back to the file. With other values than the default this should work as expected.

The reason why we drop it for 5 minutes is, we can't distinguish user contributed values from default values (if they are both the same). Otherwise we would write 5 minutes to every pdfpc file.

**Comment by Drup** [comment]
I took 5 as an example, you can reproduce with any value. 

I actually noticed that by writing to the `.pdfpc` file directly, and notice that whichever value I wrote, the section was removed the next time pdfpc rewrote the file.

**Comment by AndreasBilke** [comment]
Sorry, you are right. It should be fixed in master.
