### ISSUE TITLE
How to use without desktop environment

### ISSUE THREAD

**Issue by jan-glx** [pdfpc/pdfpc#241]
How can I use pdfpc without a Desktop environment/ via X forwarding?
I have two screens available (0.0 and and 0.1). I can view the presenter window of pdfpc on either (individually) if I specify the screen to be used using `export DISPLAY=:0.1` or `export DISPLAY=:0.0`. How can I make pdfpc use both screens at the same time and display the presentation on one of them?

**Comment by AndreasBilke** [comment]
Afaik: you can't

**Comment by einhander** [comment]
@jan-glx If you have dual monitor setup on pdfpc host, you can use  two instance of x11vnc for  each monitor. Then connect with two vncviewers from any 2 pc (or pc and tablet) to control the presentation. 
That's main idea.

**Comment by jan-glx** [comment]
Thank you for your tip, @einhander . But I am afraid it won't help me because I have no hardware screens on the host machine. @AndreasBilke thanks for the quick answer, could you tell me what the requirements in that respect are?

**Comment by jan-glx** [comment]
Turns out I was just missing a simple xinemera switch with my Xserver. It works fine now (besides videos).
This also represents an easier way to run pdfpc on windows:

1. If not done already,[ activate wsl/lxss](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide?f=255&MSPPError=-2147217396)
2. On windows, install [VcXsrv](https://sourceforge.net/projects/vcxsrv/)
3. Make the presentation screen you secondary screen in windows and disable the taskbar on that screen
4. Start the X-server with `vcxsrv -nodecoration -screen 0 @1 -screen 1 @2 +xinerama`
5. Start WSL-`bash`, run `sudo apt-get install pdfpc`, `wget https://pdfpc.github.io/demo/pdfpc-demo.pdf` and `pdfpc pdfpc-demo.pdf`
6. Enjoy

**Comment by AndreasBilke** [comment]
> @AndreasBilke thanks for the quick answer, could you tell me what the
> requirements in that respect are?

We use a single Gtk.Monitor which can have multiple screens. If I
understand you correctly you have multiple Gtk.Monitors with a single
screen on each. That's why pdfpc would not support your setup.

**Comment by pseisam** [comment]
I just migrated from Win 7 to Win 10 and now the cygwin setup I posted in issue #106 is broken (I get one huge pdfpc window with the width of both monitors instead of two separated windows on each monitor).
So @jan-glx solution came in handy. Apart from the issue, that it doesn't work for me. I get the following error after starting pdfpc in the WSL-bash:
```
Failed to connect to Mir: Failed to connect to server socket: Datei oder Verzeichnis nicht gefunden
Unable to init server: Could not connect: Verbindungsaufbau abgelehnt
(pdfpc:183): Gtk-WARNING **: cannot open display:)

```
Could you please help me to find my fault?
I followed exactly the steps you described, but for step 4) I am not sure, if I did everything right:

- 4.1: Opened cmd
- 4.2: Switched to VcXsrv install dir
- 4.3: Started X-server with vcxsrv.exe -nodecoration -screen 0 @1 -screen 1 @2 +xinerama
- 4.4: Two new X-server instances appeared which resulted in 2 black screens an each monitor

**Comment by jan-glx** [comment]
Not sure what the problem is. Which version of W10 are you on? Seems related to [this](https://github.com/microsoft/bashonwindows/issues/637#issuecomment-247044035).
Try `DISPLAY=:0.0 pdfpc pdfpc-demo.pdf` or try to apply the [dbus-fix](https://www.reddit.com/r/Windows10/comments/4rsmzp/bash_on_windows_getting_dbus_and_x_server_working/) (run `sudo sed -i 's$<listen>.*</listen>$<listen>tcp:host=localhost,port=0</listen>$' /etc/dbus-1/session.conf` and restart bash)

**Comment by pseisam** [comment]
Wow, you were just too fast with your answer. Indeed the display variable was my problem. See my updated question above.

**Comment by pseisam** [comment]
One little error in your edit, Jan. Either pdfpc should be started like this (you added the "export" part which leads to an error):
`DISPLAY=:0 pdfpc pdfpc-demo.pdf`

or the DISPLAY environment variable should be exported first like this (I just added this command to the .bashrc so that I don't have to type this every sesssion):
`export DISPLAY=:0`
and pdfpc can be started without anything else:
`pdfpc pdfpc-demo.pdf`

**Comment by jan-glx** [comment]
@pseisam or a bit too slow 😄 . Sorry about that. I had the display variable set in my .bashrc and forgot about it. Do you know if the dbus-fix is necessary here (i.e. had you applied it)? I edited the guide as proposed. 
PS: haha now you were to quick

**Comment by pseisam** [comment]
Never expected such a quick answer though ;)

Nope, the dbus-fix was not necessary here.

**Comment by jan-glx** [comment]
> Nope, the dbus-fix was not necessary here.

good to know, thanks

**Comment by AndreasBilke** [comment]
@pseisam , could you please write a PR to change the readme? I am not interested in windows related issues so you might help out? :)

**Comment by pseisam** [comment]
Of course :)
