### ISSUE TITLE
Feature request: add option to hide overlays only the first time

### ISSUE THREAD

**Issue by kiryph** [pdfpc/pdfpc#242]
When I give a presentation with overlays and I have revealed an overlay, I never want to hide this segment again. A typical situation is when someone interrupts and asks a question which requires me to switch back to the previous slide; when I proceed with the presentation, I do not want to unhide the segments again.

The html presentation framework `shower` has implemented the unhiding behavior how I want it:  https://shwr.me/#11

I would like to have the same behavior in pdfpc for example by adding a command line switch to enable this behavior.

Is it feasible to add this to pdfpc?

**Comment by AndreasBilke** [comment]
Surely it might be a nice feature. If someone is willing to implement it, I
would be happy to merge this.

**Comment by phillipberndt** [comment]
I like this idea too, but I'm not sure what'd be the best implementation.. IMHO, this shouldn't be the default, because while the default cursor key bindings make navigation inconvenient for your use case, they are straightforward to understand.

How about adding an array that counts the largest real slide already seen within each user slide, and two new keys: One to navigate to the largest real slide on the previous user slide already seen, and one to navigate to the next real slide of the current user slide if there is one, or the next unseen real slide of the next user slide else wise. Would that work?

**Comment by kiryph** [comment]
@AndreasBilke and @phillipberndt thanks for your interest in this feature.

In my opinion, this feature is something most people with overlays could like except they use overlays to replace content. However, in my experience most often overlays are used to dissect a complicated slide into smaller parts to digest. Also replacing content by overlays can make it more difficult for the audience to refer to the correct slide when asking questions and therefore one could recommend not doing it.

I agree: it should NOT become a default. As I said I would add a commandline switch to enable this behavior if desired or as suggested add new actions which the arrow keys can be mapped to.

As far as I can judge: the array suggestion (index user slide, value largest real slide already seen) sounds good.

When I can map the left and right arrow keys to the new actions

- `go to the largest already seen real slide on previous user slide`
- `go to next real slide of the current user slide if there is one otherwise go to largest already seen real slide on next user slide`

it should work as asked.

I am open for improvements to make it easier to understand and that users get a predictable behavior.

**Comment by phillipberndt** [comment]
Have a look at the [progress branch in my repository](https://github.com/phillipberndt/pdfpc/tree/progress), the feature is bound to j/k (..because both were unbound and this should be familiar to vim users ;-)) by default, but can be rebound to the cursor keys using the rc file. Does this work as intended?

**Comment by kiryph** [comment]
@phillipberndt Thank your very much for your implementation. I've tested it and it works as intended. I REALLY like this feature.

I think I will rebound to arrow keys. Using different keys for navigation can be irritating. And also in case I use a presenter/laser pointer which usually offers only the arrow keys.
