### ISSUE TITLE
Could not load cached PNG image for slide 0: Error writing

### ISSUE THREAD

**Issue by ChasNelson1990** [pdfpc/pdfpc#257]
Hi, I could not find anything similar to this mentioned in past errors so hopefully this is something new.

Background info: this is Fedora 25 system with all dependencies installed and updated through DNF. PDFPC was also installed through DNF. I'm able to successfully run both the standard demo slides and the movie-embedded slides so I think I have all the dependencies sorted.

When I try to run an old pdf compiled with custom beamer style files I get the following error:

> Could not load cached PNG image for slide 0: Error writing

As far as I can tell, with the exception of movies, I shouldn't need to do anything magical to compile this pdf, correct?

I've checked where this error comes from in the code (engine.vala line 89) but the error being spit out by the system is not overly helpful.

I have split the presentation and attached the first slide only. This single slide pdf shows the same error as the multislide pdf and saves me having to provide the whole thing.
[demo1.pdf](https://github.com/pdfpc/pdfpc/files/1188110/demo1.pdf)

Any suggestions?

**Comment by phillipberndt** [comment]
Doesn't affect me with the latest version, so all I can do is to help debugging: Yes, the PDF shouldn't be the problem. You should never see this error without an associated "Could not generate PNG cache image for slide" message preceeding it. The error [doesn't come from GtkPixbuf either](https://github.com/GNOME/gdk-pixbuf/search?l=C&q=error+writing&type=&utf8=%E2%9C%93), apparently. What happens if you use `-p` on the command line? Does a valid PNG file get written to `~/.cache/pdfpc`?

**Comment by ChasNelson1990** [comment]
I get five folders, each with a two digit name, e.g. 8e, each one containing one PNG file. Four of the folders contain a PNG of the first slide and one contains a PNG of the second slide. If I use the one slide version I get four folders all containing PNG files of that slide.
Thanks for your help.

**Comment by phillipberndt** [comment]
That means that the PDF is rendered correctly, and the PNG data stream is valid. There is an error somewhere in the code that loads the PNG again when the cache is accessed, but I do for now think that it isn't on our end. I do not currently have any ideas how to resolve this, sorry.

**Comment by ChasNelson1990** [comment]
That's okay, thanks for trying.

Can you think of anyway of getting the code to spit out where the error is coming from? I suppose if I took it out of the try-catch and recompiled then it would throw the full trace out?

**Comment by phillipberndt** [comment]
The error is coming from `classes/renderer/cache/png/engine.vala`, line 89. That's simple to determine, because it is the only place in the source code where this error message is used:

	var loader = new Gdk.PixbufLoader();
	try {
		loader.write( item.get_png_data() );
		loader.close();
	}
	catch( Error e ) {
		GLib.printerr("Could not load cached PNG image for slide %u: %s\n", index, e.message);
		Process.exit(1);
	}

The check we did earlier was to confirm that `item.get_png_data()` returns a valid PNG file. Which means that the failure must be within the `loader.write` and/or `loader.close` call, which are internal methods of GdkPixbuf.

By the way, if all you want is a way around this, try using the `-z` switch, or even `-c`. Both disable the PNG compressed cache.

**Comment by ChasNelson1990** [comment]
So, just for comparison I'm running gdk-pixbuf2-2.36.7-1.fc25.x86_64 and gdk-pixbuf2-devel-2.36.7-1.fc25.x86_64, are they the same versions as your set-up?

Aha! Using -z works as a work around... That should be fine. Maybe I'll dig into it further if it becomes a problem in the future. Thanks for your help.

**Comment by phillipberndt** [comment]
I run 2.32.2 from Ubuntu. Great to hear that the workaround helps; I'll close this for now. Feel free to comment/reopen if the problem resurfaces!
