### ISSUE TITLE
Presenter keys advance to next bookmark instead of next slide

### ISSUE THREAD

**Issue by sergiud** [pdfpc/pdfpc#258]
My presentation contains section bookmarks and whenever I hit the next key on the presenter, `pdfpc` jumps to next bookmarked slide instead of simply advancing to the next slide. Hitting the right keyboard key works though.

Might be related to #255.

**Comment by AndreasBilke** [comment]
Could you give a mwe?

**Comment by sergiud** [comment]
Do you need a beamer document or a PDF?

**Comment by AndreasBilke** [comment]
Both :)

**Comment by AndreasBilke** [comment]
I can't follow you. Next key (you mean Page Down?) and the Right key are mapped to the same function within pdfpc.

**Comment by sergiud** [comment]
> I can't follow you. Next key (you mean Page Down?) and the Right key are mapped to the same function within pdfpc.

This maybe true but I still experience the issue with some PDFs. I'm still trying to create a MWE from my presentations.

**Comment by AndreasBilke** [comment]
@sergiud you mentioned #255. This issue was fixed in master. Is your issue also fixed there?

**Comment by HermannDppes** [comment]
In your MWE, the Methodology slide is (incorrectly) recognized as the third overlay in a single slide. This due to all three of them (both Motivation page 2s and the Methodology title) having pdf page number 2.

**Comment by HermannDppes** [comment]
I unfortunately need to do other things now, but something resembling an actual *minimal* working example is attached. The problem seems to boil down to your theme counting the title slides in a strange way (i.e., not giving them their own page number but attaching them to the previous). IANAM [1] but this is a bug in your theme, not in pdfpc. Probably trivial to fix by any skilled LaTeXnician.

[slides.zip](https://github.com/pdfpc/pdfpc/files/1245197/slides.zip)
[ssvo.pdf](https://github.com/pdfpc/pdfpc/files/1245194/ssvo.pdf)

[1]: I am not a maintainer. This is in no official capacity, but from one user to another.

**Comment by sergiud** [comment]
The theme is perfectly fine. There's a good reason why outline slides are not given their own slide numbers: to ensure only content slides are numbered and this without gaps. Besides, every other PDF viewer is able to handle the slides. Blaming the issue on the theme is of course the easy way out.

**Comment by AndreasBilke** [comment]
@sergiud pdfpc uses page labels to detect overlays. if someone (like the theme) is doing unpredictable things, pdfpc cannot handle overlays on itself. *But* you can disable auto grouping of overlays via command line. Then pdfpc will just put one slide after another. Could you try this?

**Comment by sergiud** [comment]
@AndreasBilke This works, thanks!

**Comment by AndreasBilke** [comment]
Then I will close this.
