### ISSUE TITLE
Slider counter and timer drift out of the screen

### ISSUE THREAD

**Issue by AndreasBilke** [pdfpc/pdfpc#26]
During testing I discovered a bug  on the current master. With every time you switch between the presenter and the overview the slide counter and timer drift south east (see screenshot). If you `tab` quite a lot the counter and timer disappear completely.

I tested this issue also in window mode and it seems that the window size of the overview is slightly heigher than the presenter. Maybe I find some time to bisect the point where this was introduced. Within the old davvil/pdfpc version this does not happen.

![screen-drift](https://cloud.githubusercontent.com/assets/1804398/6504215/0c7ea1c2-c335-11e4-9042-ced71ccd629a.png)

**Comment by andybarry** [comment]
Interesting.  My system has looked like this even when it first comes up.  It's been a long standing issue for me (years), so perhaps this is related.  If not I'll investigate my issue and file a new bug.

**Comment by AndreasBilke** [comment]
Is your counter/timer also drifting (moves some pixels each switch between
overview and presenter) towards south east or are counter/timer displaced
from start on and does not move with switching?

**Comment by andybarry** [comment]
In fullscreen mode it moves south east after my first switch.  Doesn't move after that.  Never moves in windowed mode, but starts misaligned.

**Comment by rschroll** [comment]
I've just merged in #25, which may change this behavior.  Prior to 
that, I got a vertical jump when switching between the slide and 
overview.  Now, it's rock steady.

If this doesn't solve it and you start trying to track it down, the 
first place I'd look would be the GTK 2 -> 3 transition.

**Comment by AndreasBilke** [comment]
Okay with git bisect (this was really helpful) I found that with the commit
of 5d90a3d (merge of rschroll/iconview) the bug started. I have no idea
why.

**Comment by AndreasBilke** [comment]
Maybe I found the problem. Could someone test if I broke something? For me it works now.

**Comment by rschroll** [comment]
I put that bit of code in for the overview key handling.  For reasons I 
don't understand, when I pass keystrokes to the overview icon view, it 
will only handle them if it has focus within the window and the window 
has top level focus.  So that bit of code tries to make sure this is 
so.  If we remove it, it'd be possible to get the focus into the 
presentation window, and some keystrokes wouldn't work in overview mode.

I don't see why this should cause re-layout at all.  The present() code 
should just give the top level window focus.  Could you try changing 
that if statement to
	if (top != null && !top.has_top_level_focus)
and see if that solves your problem (at least when you don't move the 
focus away from the presentation window)?

Out of curiosity, what version GTK are you running?  I'm on 3.10.

**Comment by AndreasBilke** [comment]
I added the has_toplevel_focus, this also fixed the issue. I updated the branch and will create a pull request.
I am on arch linux and using the latest gtk version 3.14.9
