### ISSUE TITLE
Feature request: play video together with its subtitle file

### ISSUE THREAD

**Issue by Globulle** [pdfpc/pdfpc#328]
### Expected Behaviour
Most video players automatically load the subtitle file (`.srt` file for example) if present when it has the same name than the video file. It should be great to get the same behavior with `pdfpc`.

### Actual Behaviour
When a video is played, it ignores the presence of a subtitle file.

**Comment by fnevgeny** [comment]
1. I don't think that automatically loading an .srt file would be the right behavior. Especially since the video file may be provided as a remote URI.
2. There is no proper support in the `multimedia` package for specifying a subtitle file/URI.

We can come up with a hack, of course (e.g., in the form of video_file@srt_file). But videos in PDFs prepared this way would be seen only by pdfpc. Any other idea?

**Comment by Globulle** [comment]
When I need to include video I'm already stuck at using `pdfpc`, I don't use the `multimedia` package. The hack would be enough for me but I'm not sure to be able to code it.

**Comment by fnevgeny** [comment]
> I don't use the `multimedia` package.

Do you use `\href`directly?

**Comment by Globulle** [comment]
> Do you use `\href` directly?

No, I use `\inlineMovie` or `\fullFrameMovie` proposed in `pdfpc-commands.sty` given [here](https://pdfpc.github.io/demo/pdfpc-video-example.zip).

**Comment by fnevgeny** [comment]
Well, it boils down to `\href` anyway. This can easily be extended to include suburi. I'll think about it.

**Comment by AndreasBilke** [comment]
But keep in mind that href is buggy. I don't like building things on bad things.

**Comment by fnevgeny** [comment]
> href is buggy

In which sense?

**Comment by AndreasBilke** [comment]
See the man page. We discourage the users from using it. (I think when you combine notes and videos)

Am 9. November 2018 22:42:32 MEZ schrieb Evgeny Stambulchik <notifications@github.com>:
>> href is buggy
>
>In which sense?

**Comment by fnevgeny** [comment]
> See the man page. We discourage the users from using it. (I think when you combine notes and videos)

Yes, I recall there was an issue with this combination (which might be a beamer issue, since, after all, the `hyperref` package is included by beamer). Anyway, since we support the direct `\href` links, I see no reason not to extend this support to subtitles, especially if it requires no extra efforts.

In the case of `\href` we already use a hack to pass extra options in the `GET` URI-style (`?*`), so e.g., `srtfile=<filename_or_uri>` can be used. The "good" `\movie` command from the `multimedia` package allows for passing options in a civilized way, but only predefined ones. Which means we either should use the same hack as with `\href`, or submit a feature request to `beamer` (and it will take quite some time, if accepted, to propagate to distributions/end users).

Which other variants are out there? I wouldn't like searching for srt files automatically (based on the video pathname), as this seems a rather rarely used feature in presentations, introducing unnecessary filesystem or even network lookups in > 90% of cases.

**Comment by fnevgeny** [comment]
> Because we give people "reasons" to use `\href` for it, which results (in some cases) in poor experience.

Well, if there is a single biggest reason to use `\href`, it must be `pdfpc-video-example`, which we kind of officially recommend :)

> But with `\href` we need in any case a hack, right? With `multimedia` we either hack or have a chance to get a clean solution?

Right. Maybe we should supply our own `.sty` supporting the features we want and ignoring any "antifeature"... There are also other valid (IMHO, at least) reasons for it (#300).

> Make an option? :) Like "search for subtitles automatically"?

Maybe. But I think it's an overkill. Even in a single presentation, not all videos would necessarily have subtitles, certainly it shouldn't be a global pdfpcrc option. So a .pdfpc option then, plus a command-line flag to init it... Isn't it a hack (OK, workaround) by itself?

**Comment by AndreasBilke** [comment]
> Well, if there is a single biggest reason to use `\href`, it must be
> `pdfpc-video-example`, which we kind of officially recommend :)

True, but this is something I want to get rid of :)

> Right. Maybe we should supply our own `.sty` supporting the features we
> want and ignoring any "antifeature"... There are also other valid (IMHO,
> at least) reasons for it (#300).

Hm, I don't see the connection between both issues?

> Maybe. But I think it's an overkill. Even in a single presentation, not
> all videos would necessarily have subtitles, certainly it shouldn't be a
> global pdfpcrc option. So a .pdfpc option then, plus a command-line flag
> to init it... Isn't it a hack (OK, workaround) by itself?

Almost every command line option feels like a hack to me :) If it's a
per-presentation option then people may be don't know that this feature
exist? But still, a command line per-presentation option is (for me) far
better than a URI hack.

**Comment by fnevgeny** [comment]
> True, but this is something I want to get rid of :)

Fine with me. Shall we combine pdfpc-video-example and pdfpc-demo (both updated, of course) into something like pdfpc-tutorial, to become part of, and distributed together with, pdfpc itself? 

> Hm, I don't see the connection between both issues?

Only that both imply something like `pdfpc.sty`. With an "official" pdfpc LaTeX package, we should be able to provide `\movie` (or `\pdfpcmovie`) that is always in sync with the current pdfpc capabilities.

> a command line per-presentation option is (for me) far better than a URI hack.

OK, point taken :)

**Comment by AndreasBilke** [comment]
> Shall we combine pdfpc-video-example and pdfpc-demo (both updated, of
> course) into something like pdfpc-tutorial, to become part of, and
> distributed together with, pdfpc itself?

I'm not sure. I'm a big fan of well written man pages (also with examples)
Shipping .sty files hurts my unix feelings :). But a new pdfpc demo as
itself is a good idea.

> Only that both imply something like `pdfpc.sty`. With an "official" pdfpc
> LaTeX package, we should be able to provide `\movie` (or `\pdfpcmovie`)
> that is always in sync with the current pdfpc capabilities.

Actually I also don't like the pdfcpc.sty :) It's just a wrapper over
normal latex commands. And it hides details.

Do we want to adapt the current pdfpc-demo? It's kind of a tutorial but
maybe people should read the man page for the key binding. But the basic
movements are actually standard and not note worthy.

I think it is more useful to demonstrate all features pdfpc supports
(Overlays, Movies, Beamer notes(?))

**Comment by fnevgeny** [comment]
> With `multimedia` we either hack or have a chance to get a clean solution?

In fact, a clean solution is unrealistic in a near future. The problem is poppler doesn't even support majority of _present_ `multimedia` options - only `loop` and `showcontrols`. It's mentioned in `movie.vala`... So realistically, if we want to support more than these two options, a URI hack seems unavoidable. And for some, a configuration/command-line flag isn't an option - like start=, stop=, etc, which are defined per video.

**Comment by fnevgeny** [comment]
> Actually I also don't like the pdfcpc.sty :)

Did you mean `pdfpc-commands.sty` from `pdfpc-video-example`? It isn't what I had in mind...

> I think it is more useful to demonstrate all features pdfpc supports (Overlays, Movies, Beamer notes(?))

I agree.

**Comment by fnevgeny** [comment]
I have finally realized that the `multimedia` package supports _all_ movie features defined in the [PDF standard](https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf), Sec. 13.4; but a subtitle file specification is not there. The glib binding of poppler lacks support for some of the standard options, and a patch would be trivial, but it wouldn't solve the principal limitation of the standard itself...

Actually, these features are officially "obsolescent and their use is no longer recommended. They are superseded by the general multimedia framework described in 13.2, “Multimedia.”"...

It seems we've no other choice but guesswork based on media basename (and subject to a run-time option).

**Comment by AndreasBilke** [comment]
> It seems we've no other choice but guesswork based on media basename (and
> subject to a run-time option).

So it becomes an automatic detection/loading based on a command line option
(per pdf, saved in .pdfpc file)?

**Comment by fnevgeny** [comment]
> So it becomes an automatic detection/loading based on a command line option (per pdf, saved in .pdfpc file)?

I think so...

**Comment by fnevgeny** [comment]
In the end, I didn't implement storing this preference in .pdfpc. In principle, it should be possible to specify (in .pdfpc) subtitle file per video, where required. This assumes the .pdfpc file (or its equivalent) is generated by LaTeX, as discussed in #300.

**Comment by AndreasBilke** [comment]
Implemented by fnevgeny with #398
