### ISSUE TITLE
Troubles on Windows subsystem

### ISSUE THREAD

**Issue by Steinerkadabra** [pdfpc/pdfpc#384]
Hello, I am trying to run pdfpc on my windows linux subsystem.
Running pdfpc on a single monitor works perfectly, in single slide mode as well as in presentator mode. Yet, when I am trying to set up a presentation on two screen it behaves unexpected. I am using exactly the steps you describe in the point 'On Windows 10 (with Windows Subsystem for Linux (WSL)):' in your readme. But instead havin the presentator mode on one screen and the presentation on the second screen somehow pdfpc connects both screens and shows the presentator mode over the combined two screens? Do you have any idea on what it is that I am doing wrong?

Thank you in advance!

**Comment by maehne** [comment]
As a workaround, you might consider to build `pdfpc` natively under Windows 10 using the MinGW-W64 toolchain of [MSYS2](http://www.msys2.org/). MSYS2 contains all necessary dependencies to to build `pdfpc`. GTK+-3 apps then run natively as a normal Windows application. So far, it works quite well for my needs (though, I don't use PDF slides with embedded videos).

Here are my notes to build `pdfpc` (I didn't yet get around to try to formalize it into a package for automated installation through MSYS's `pacman` tool:

1. Install build dependencies:
```
pacman -S mingw-w64-x86_64-cmake
pacman -S mingw-w64-x86_64-ninja
pacman -S mingw-w64-x86_64-pkg-config
pacman -S mingw-w64-x86_64-vala
```
2. Install library dependencies:
```
pacman -S mingw-w64-x86_64-gtk3
pacman -S mingw-w64-x86_64-libgee
pacman -S mingw-w64-x86_64-poppler
```
3. Patch the sources

- Need to add `add_definitions("-D_POSIX_C_SOURCE")` to src/CMakeLists.txt. Otherwise, symbol `localtime_r` won't be found (cf. to [MSYS2 Wiki](https://github.com/msys2/msys2/wiki/Porting)).

- Need to add [own implementation](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-libkml) of `strptime()`.

4. Configure and build:
```
mkdir build
cd build/
cmake .. -G Ninja -DMOVIES=off -DCMAKE_INSTALL_PREFIX=/mingw64
cmake --build . --target install
```
5. Optionally, add shortcut "PDF Presenter Console" to the `shell:sendto` folder

Ressources:
1. [Installing GTK+ and its dependencies](https://www.gtk.org/download/windows.php)
2. [How to build your GTK+ application on Windows](https://blogs.gnome.org/nacho/2014/08/01/how-to-build-your-gtk-application-on-windows/)

**Comment by Steinerkadabra** [comment]
Thank you for your advice!
Unfortunately, I will need to run embedded videos in my slides..

**Comment by maehne** [comment]
You might be able to make the video playback work also on MSYS2. The MinGW-w64 packages repository contains also packages for Gstreamer. I just did not yet find the time to try it out myself. You will need to install at least the package `mingw-w64-gst-plugins-good` and all its automatic dependencies. Then, you may try to build `pdfpc` as described above only now specifying `-DMOVIES=on`.

**Comment by Steinerkadabra** [comment]
I am now trying to follow your instruction. Unfortunately, I have absolutely no idea how to ' add own implementation of strptime()' ..
Would you be able to explain me what I have to do?
Thank you!

**Comment by Steinerkadabra** [comment]
Thank you, now two more questions..
I fail to install ingw-w64-gst-plugins-good while trying to do `pacman -S ingw-w64-gst-plugins-good`. I receive the error that it does not find the target.
Second, i did the two steps in step 3 in my download file where I have this pdfpc files. Yet, how do i get them somewhere where mysy can use them? 
I am sorry for such basic questions!

**Comment by Steinerkadabra** [comment]
First question is clear now, i needed to add -x86_64 after which I was able to install it..

**Comment by Steinerkadabra** [comment]
Running step 4 I get the error cmake is not available...
I copied the pdfpc folder from the website with the additions form step 3 into my msys64 folder and tried to run step 4 from the pdfpc folder. Anything I did wrong?

**Comment by maehne** [comment]
To compile `pdfpc`, you have to launch MinGW-w64 command prompt. In the MSYS2 command prompt, the MinGW-w64 toolchain is not in the path, including the compatible CMake version, which you should have installed in step 1.

**Comment by maehne** [comment]
I tried to build `pdfpc` with video playback support on Windows 10 using the MinGW-w64 toolchain of MSYS2. Even though, the program builds just fine, video playback doesn't work. Have a look to issue #386 for details. (Don't get confused by the issue title -- I first observed the problem on macOS.)

**Comment by Steinerkadabra** [comment]
I am experiencing the same issue...

**Comment by fnevgeny** [comment]
I assume the #391 patch fixes the bug. If not, please reopen the issue.
