### ISSUE TITLE
Move to GStreamer 1.0

### ISSUE THREAD

**Issue by rschroll** [pdfpc/pdfpc#4]
pdfpc currently uses the rather old GStreamer 0.10.  This is causing some codec problems on modern machines (davvil/pdfpc#86).  I believe the best solution is to move to GStreamer 1.0.  I have [a branch](https://github.com/rschroll/pdfpc/tree/gst1.0) that seems to mostly work, although video scaling is a bit wonky (or possibly correct).  We used to distort the video to fill whatever rectangle it's associated with.  Now, gstreamer is, by default, adding black bars to avoid the distortion.  I've only managed to turn this off for the first video output.  But perhaps we should leave it this way, in which case we need to adjust the code that draws the progress bar.

**Comment by andybarry** [comment]
I think leaving the black bars sounds reasonable.  Preserving the aspect ratio makes sense to me.

**Comment by Beuh** [comment]
After some testing on my side, what I found is that : 

  - Video playback works fine on that branch on my pdfs, with various formats and video sizes. Asspect ratio is I think a minor problem since a latex code with an image thumbnail the same size as the video does the trick. In case a custom rectangle is assigned to the video, I would also say that preserving the aspect ratio makes sense

  - As before in pdfpc with gstreamer-0.1, the autoplay and loop (I did not look at showcontrols) commands do not work. It is not an issue with poppler since it works fine in okular, probably just an issue of implementing it in pdfpc. Could be worth looking at !

**Comment by rschroll** [comment]
The problem I'm having at the moment is that the overlay for the 
controls is getting the size of the box (which I think is a change from 
0.10), not the size of the movie, but it's still being squashed to 
cover only the frame of the movie, not the full area.  Not only does 
this result in them being squashed, it means they registration is off 
wrt mouse position.

Argh.

**Comment by AndreasBilke** [comment]
Is there some progress here? If there is a working state (but contains bugs) I think it would be worth to push it to master to drop gstreamer 0.10 dependencies. We would than be in a state where all old stuff is removed in favoir to new libraries.

**Comment by rschroll** [comment]
No progress, I'm afraid.  I asked about it on the gstreamer mailing 
list, but got no responses.  I think I'll need to cook up a better test 
case and ask about it again.

In the meantime, I think it'd be okay to merge this in and open a bug 
about the aspect ratio problem.  I want to squash that eventually, but 
most of the time the aspect ratios will match.  I'll go ahead and 
propose a merge.

**Comment by rschroll** [comment]
We've moved to GStreamer 1.0 with #36.  See #44 for the aspect ratio problem.
