### ISSUE TITLE
Redundant space between next slide and notes (regression?)

### ISSUE THREAD

**Issue by Minecrell** [pdfpc/pdfpc#438]
Compared to pdfpc 4.3.2 there is quite a bit of space between the next slide and the notes.

**Expected Behaviour**
This is the same presentation on pdfpc 4.3.2:

![Screenshot_20190529_130851](https://user-images.githubusercontent.com/3035868/58552779-83477a80-8213-11e9-924e-0b664fae8398.png)

**Actual Behaviour**
There is quite a bit of redundant space between the next slide and the notes, space that could be used for additional notes etc...

![space](https://user-images.githubusercontent.com/3035868/58553139-6cedee80-8214-11e9-8f29-6a3ef2aee4f0.png)

**Steps to reproduce**

1. Open pdfpc with these example slides: [example.pdf](https://github.com/pdfpc/pdfpc/files/3232171/example.pdf) (the effect varies with different aspect ratios)
2. Add some notes

Is this intended? If so, is there any way to reduce that space?
I believe this was introduced in https://github.com/pdfpc/pdfpc/commit/168039268158f46f3881dd0f8a4e28f5c999254c, it doesn't happen before that commit.

pdfpc version: master (fce820972424e4fb24186a7f80e935cee1090c50)
Used Distribution (GTK version, vala version): Arch Linux (Gtk3 3.24.8, Vala 0.44.3)
Display Server (X/Wayland): X
HiDPI Setting (yes/no): no

**Comment by fnevgeny** [comment]
You can fine-tune it by varying (decreasing) value "0.55" in [this line](https://github.com/pdfpc/pdfpc/blob/fce820972424e4fb24186a7f80e935cee1090c50/src/classes/window/presenter.vala#L599), but it will not be universal across different aspect ratios of monitors and presentations.

I wouldn't like to make a proper fix at this moment since the layout of the GUI for 4.4 is not finalized yet, anyway.

**Comment by fnevgeny** [comment]
@Minecrell, please test #469 .
