### ISSUE TITLE
Only use windows mode for presenter, but fullscreen for audience window

### ISSUE THREAD

**Issue by knarrff** [pdfpc/pdfpc#466]
**Only submit a feature request if you read the SUPPORT.md file**

I did.

The feature wish description:

First of all, I am still using version 4.0.5, but I read though the current CHANGELOG and didn't see any mention of the change I'd really like to see. If I somehow missed it and it is already implemented, then I apologize.

What I find myself often doing is using the split (full)screen for presentation. However, while displaying a slide I then want to do something else on my own presenter screen, like managing an online-feedback system while showing the link to said system to the audience, or whatever. At the moment I don't see how I can do this without leaving the presentation. The only somewhat workable option is to use windowed-mode and specifying the size of the presenters screen as window size, but that would still leave the "ugly" window decorations. To me it seems, at the moment, there is only the choice between having only-windowed or only-fullscreen mode, not a mixed mode in which the presentation is fullscreen, but the presenter screen is an actual window - and that is what I propose to have added.

Before diving into the code: am I right that this is currently not yet possible, and if so: do you see any large obstacle providing this? Are there any other objections one could have against this proposal?

**Comment by fnevgeny** [comment]
It's implemented in the master branch; the option is `-w presenter`. And you can switch between the full screen and windowed modes (of the presenter alone) by pressing `w`. In fact, I think it might be the preferable default option for startup (presenter in the windowed mode). Otherwise, some window managers don't really know what size to assign to a window in the "windowed" mode if they have never seen that before.
