### ISSUE TITLE
Notes not saved on crash

### ISSUE THREAD

**Issue by mlthlschr** [pdfpc/pdfpc#473]
In case the app crashes (or is being forcefully closed), all notes of this session are being lost. The only hope are the "Found conflicting notes for slide xx" messages via stdout. Would be great if the notes would be saved once in a while, otherwise quite a lot of work is simply lost.

**Comment by fnevgeny** [comment]
> In case the app crashes

First, we would like to receive reports on any crash. Second, if an app crashes, nobody can ensure it will do something _reliably_. Especially in a language like Vala with automated memory management.

> (or is being forcefully closed)

One may forcefully close pdfpc exactly for this purpose - to avoid saving notes (or more generally, the .pdfpc file). How can we distinguish? And why would one normally want to kill the app instead of pressing `Ctrl+Q`?

**Comment by mlthlschr** [comment]
Thanks for patronizing. Looks like you do not appreciate constructive feedback.
