### ISSUE TITLE
Display umlauts in notes

### ISSUE THREAD

**Issue by CoreCube** [pdfpc/pdfpc#579]
**Actual Behaviour**

The `ä` isn't correctly displayed as a note.
There is some weird text: 
```
unhbox voidb@x group let unhhox
voidb@x setbox @tempboxa hbox
{aglobal mathchardev
accent@spacefactor spacefactor }let
egingroup endgroup elax let
ignorespaces elax accent 127 aegroup
spacefactor accent@spacefactor
```

**Steps to reproduce**

Compile with `pdflatex`
```
\documentclass{beamer}
\usepackage[utf8]{inputenc}
\usepackage{kvoptions}
\usepackage{xstring}
\usepackage{pdfcomment}
\usepackage{hyperxmp}
\usepackage{pdfpc}
\begin{document}
\begin{frame}
	ä
	\pdfpcnote{ä}
\end{frame}
\end{document}
```

pdfpc version: v4.5
Display Server (X/Wayland): X

**Comment by fnevgeny** [comment]
You miss `\usepackage[T1]{fontenc}`

Instead of attaching a real file, you copy&pasted its contents, so it isn't clear what exact input encoding you use. It seems it's actually latin1, so I had to add `\UseRawInputEncoding` for the example to work at all (or change `\usepackage[utf8]{inputenc}` to `\usepackage[latin1]{inputenc}`).

BTW, you only need `\usepackage{pdfpc}`, the dependencies (`kvoptions` etc) are loaded automatically.

**Comment by CoreCube** [comment]
Thank you for your help. That was the issue.

**Comment by MartinX3** [comment]
Sadly none of the mentioned packages worked for me.

Also `\usepackage[latin1]{inputenc}` gave me
```/usr/share/texmf-dist/tex/latex/base/inputenc.sty:165: Package inputenc Error: 
inputenc is not designed for xetex or luatex.
(inputenc)                only UTF-8 supported.```

I think I will open a new issue ticket.
