### ISSUE TITLE
Could NOT find Vala (missing: VALA_EXECUTABLE) (Required is at least   version "0.26")

### ISSUE THREAD

**Issue by mrueg** [pdfpc/pdfpc#58]
Without this [1], Vala_CMake[2] is unable to find 0.26, as I don't have a regular "valac" on my system, just "valac-0.26".

[1] https://github.com/chubinou/Vala_CMake/commit/cad6d5bf6441de490951ac523a4453801aba26ef
[2] https://github.com/jakobwesthoff/Vala_CMake

**Comment by AndreasBilke** [comment]
If I understand git submodules correct, we have no chance to include such
patches without the help of the submodule maintainer (except if we do some
git hook patching on our own).

@rschroll do you think it is an option to simply copy Vala_CMake from
jakobwesthoff and do whatever we want with it?

**Comment by mrueg** [comment]
Yep, unfortunately. You might want to fork it into pdfpc's project scope and attach the fix there?

**Comment by rschroll** [comment]
This issue was only reported to upstream 5 days ago.  (And not 
particularly well -- it's hidden inside another pull request.  Let's 
give upstream a few more days before we worry about fixing it ourselves.

That said, Vala_CMake is just two small files that don't have much 
churn, so it wouldn't be unreasonable to just stick those files in our 
repository and update them by hand as needed.

**Comment by AndreasBilke** [comment]
> That said, Vala_CMake is just two small files that don't have much 
> churn, so it wouldn't be unreasonable to just stick those files in our 
> repository and update them by hand as needed.

That would be a good idea for another reason: github does not include
submodule code when you download a "release" from our github page. In fact
the downloadable release zip is unusable for our project.

I attached a tarball with the submodule code included to our current
release to make download & build easy.

**Comment by AndreasBilke** [comment]
In #59 I copied the cmake vala project into our source tree. If we merged this, we can patch our version.

**Comment by AndreasBilke** [comment]
@mrueg could you try to specify your valac compiler with
```
cmake -DVALA_EXECUTABLE:NAMES=vala-0.26 ..
```
and check if it now finds your compiler?

**Comment by mrueg** [comment]
@AndreasBilke yes, now valac-0.26 is found.

**Comment by AndreasBilke** [comment]
Okay, so should write a note into the readme how to resolve such issues.

**Comment by oquidave** [comment]
Hey, I've the same issue, but I don't see a clear solution for it.

**Comment by AndreasBilke** [comment]
Did you try the "Compiling Trouble Shooting" section in the README?

**Comment by telamon25** [comment]
> @mrueg could you try to specify your valac compiler with
> 
> ```
> cmake -DVALA_EXECUTABLE:NAMES=valac-0.26 ..
> ```
> and check if it now finds your compiler?
the actual functional line is:
cmake -DVALA_EXECUTABLE:NAMES=valac ..
then when cmake makes the file, it will say something like:
found version 0.42.2 of valac (if its installed appropriately)

here's the install instructions for valac:
https://askubuntu.com/questions/910443/how-to-install-vala-on-ubuntu-16-10

knowing all this is necessary to install a crossfile game on ubuntu linux because the bloody debian package for it doesn't seem to be found anywhere for me, so I had to compile it myself.  bleh.

**Comment by fnevgeny** [comment]
How is your rant related to pdfpc?
Modern Ubuntu installs Vala with the soft links so finding valac is guaranteed. And on ancient installations you cannot compile current pdfpc anyway.
