### ISSUE TITLE
Possible perfect portable presenter

### ISSUE THREAD

**Issue by docop** [pdfpc/pdfpc#629]
Hi  So your app is quite great and i wonder if it can be made fully portable/accessible everywhere. As to boot a pc with a linux boot iso and then just open your soft as appimage. Will it be possible to make pdfpc available as appimage for like ubuntu...
Thanks in advance and happy new year.

**Comment by fnevgeny** [comment]
Well, I'm not sure it is necessary. Typically, the latest stable version is available on the latest Debian-based (and probably others) live ISO's, e.g., Ubuntu-21.10. From there, just `sudo apt-get install pdfpc`.

**Comment by jspitz** [comment]
I think what the OP means is a way to run `pdfpc` on systems where it isn't available. For instance I find myself most of the time falling back to stock PDF viewers since I have to present at locations where I have no access to software selection (University lecture halls and conferences with preset computers). I don't think this is at all possible, but of course it would be cool if one could simply plug in a stick in these cases and issue pdfpc from it.

**Comment by fnevgeny** [comment]
Have a look at [qxpdfpc](https://github.com/pdfpc/qxpdfpc) (which is still in its infancy). You need only a browser on the conference computer.
