### ISSUE TITLE
Wrong next slide preview into presenter windows for pdf with notes 

### ISSUE THREAD

**Issue by henrythebuilder** [pdfpc/pdfpc#65]
Hi,
I have a problem with the presenter view when the pdf have notes.
In this situation the next slide preview does not seam to correspond to the correct next slide.
I use pdfpc build from git and latex beamer v 3.36 on Debian Jessie. 

To reproduce this issue I checkout the default beamer generic talk file `generic-ornate-15min-45min.en.tex` into the `solutions` folder, then first I add the two lines:
```latex
\usepackage{pgfpages}
\setbeameroption{show notes on second screen}
```
after the first line 
```latex
\documentclass{beamer)
```
then I add a note into an existing slide as:
```latex
\begin{frame}{Make Titles Informative. Use Uppercase Letters.}{Subtitles are optional.}
  % - A title should summarize the slide in an understandable fashion
  %   for anyone how does not follow everything on the slide itself.

  \begin{itemize}
  \item
    Use \texttt{itemize} a lot.
  \item
    Use very short sentences or short phrases.
  \end{itemize}

  \note{This slide isn't previewed on presenter window.} %this is the new line for a sample note !!!

\end{frame}
```

Running pdfpc with `pdfpc -n right generic-ornate-15min-45min.en.pdf` produce this issue, the slide with note was never previewed.
This is a my configuration/composition problem or is it a bug? 
Note that the default pdf, without any changes seam to work correctly.
Thanks for your work on pdfpc

**Comment by rschroll** [comment]
Can you share with us the problematic PDF file?  If you can't find a 
place to upload it, you can email to me at rschroll at gmail.

**Comment by AndreasBilke** [comment]
I googled the `generic-ornate-15min-45min.en.tex` file, your small example
is not affected of your issue.

First of all, it is a beamer bug (or pgfpages), not pdfpc. I will explain
it now:

The problem comes with the usage of beamer overlays and notes. pdfpc is
trying to find overlay pages with the help of pdf page labels. Normally,
beamer creates the same page label for pages which belongs together. The
problem arises if you use beamer notes on `a second screen`. This totally
destroys the page labels and pdfpc can't find pages which belongs togther.

This is a long standing bug in pgfpages (which is beamer using) and it is
in doubt if it ever will be fixed.

See https://bitbucket.org/rivanvx/beamer/issue/228/wrong-pdf-labels-per-page-when-using-notes

So you have two possible solutions: don't use overlays if you want notes or
don't use notes if you want overlays.

**Comment by henrythebuilder** [comment]
Hi all,
many thanks for the support about my problem !
By your explanation I understand the problem isn't into pdfpc, sorry for my original message.
HoweverI have push my sample files into a temporary repository on github (https://github.com/henrythebuilder/sample_files/tree/master/beamer_samples): the tex file (original and modified version) and the pdf produced with notes.
Thanks again.

**Comment by rschroll** [comment]
Thanks -- it's always good to have a variety of test files.

Andreas has already explained the problem, but I wanted to point out 
that you can change whether a slide should be considered part of an 
overlay by pressing 'o' when that slide is displayed.  If you do that 
for your problematic slide, it will be displayed as a full preview and 
not an overlay preview.  Note that these settings are saved in the 
.pdfpc file, so you can fix it once and then have it be correct during 
your presentations.

**Comment by henrythebuilder** [comment]
This is a really useful option for this kind of slide, I admit that I had not understood and considered this option from the manual.
With this option the preview seam ok and pdfpc produced the file `generic-ornate-15min-45min.en.pdfpc` with:
```
[file]
generic-ornate-15min-45min.en.pdf
[skip]
2,6,8,10,11,
```
Thanks @rschroll for the tip :thumbsup:
