### ISSUE TITLE
cmake fails on OS X

### ISSUE THREAD

**Issue by maxheld83** [pdfpc/pdfpc#74]
I've spent some time `brew install`ing the bejeesus out of my machine, but I still can't get `cmake` to work:

```
-- checking for module 'gdk-x11-3.0'
--   package 'gdk-x11-3.0' not found
```

I have no idea what this is or where to find it, but I *have* installed all of the listed dependencies (I think).

**Comment by alistairmcmillan** [comment]
Multiple problems on OSX. Though I'm sure a smarter man could overcome them all. :)

http://apple.stackexchange.com/a/205645/4007

**Comment by maxheld83** [comment]
thanks so much @alistairmcmillan – that's what I feared. 
Hope this great tool will be available easily on OS X soon, can't wait to use it and drum up support.

**Comment by AndreasBilke** [comment]
One solution might be to use "gdk-3.0" instead of "gdk-x11-3.0". Currently, we are using a gdk-x11-3.0 feature in the movie code. Maybe @rschroll can answer the question if it is possible to use the generic gdk-3.0 package instead of the x11 one.

**Comment by alistairmcmillan** [comment]
I tried changing src/CMakeLists.txt to point to "gdk-3.0" instead of "gdk-x11-3.0" and `cmake` now completes successfully.

`make` fails on one line though.

    /Users/alistair/Documents/pdfpc/src/classes/presentation_controller.vala:903.30-903.36: error: The symbol `X11' could not be found
                return (uint*) ((Gdk.X11.Window) view.get_window()).get_xid();
                                 ^^^^^^^
    Compilation failed: 1 error(s), 0 warning(s)
    make[2]: *** [src/classes/action/action_mapping.c] Error 1
    make[1]: *** [src/CMakeFiles/pdfpc.dir/all] Error 2
    make: *** [all] Error 2

That seems to be the only thing specific to the X11 backend. The rest compiles okay.

I tried to find an equivalent to get_xid() that works with all GDK backends, but can't find one.

**Comment by maxheld83** [comment]
+1.
Same error as @alistairmcmillan here, when trying with `gdk-3.0`.

**Comment by AndreasBilke** [comment]
That is no surprise since we use currently X11 (only) features. After some
googeling it seems unclear to me if we can support other platforms than X11
for movie playback.

At
http://docs.gstreamer.com/display/GstSDK/Basic+tutorial+5%3A+GUI+toolkit+integration
they show gstreamer gdk examples which uses platform dependent gdk calls like

```
#elif defined (GDK_WINDOWING_QUARTZ)
  window_handle = gdk_quartz_window_get_nsview (window);
```

to do the magic. I didn't found the appropriate gdk calls as vala bindings so
far.

**Comment by AndreasBilke** [comment]
I don't see the possibility to drop gdk-x11 dependency. it is used for the movie playback code. One could write some code to make movie playback optional (and therefore gdk-x11 not needed).

**Comment by AndreasBilke** [comment]
I don't see the possibility to drop gdk-x11 dependency. it is used for the movie playback code. One could write some code to make movie playback optional (and therefore gdk-x11 not needed).

**Comment by rschroll** [comment]
When I wrote the movie code originally, the only way to handle video with GTK was directly through the windowing layer.  (Which, frankly, was insane!)  Things have progressed slightly since then, so we have a few options:

1) [gtkgst](https://github.com/ystreet/gtkgst) provides cross-platform video rendering via Cairo or OpenGL.  There doesn't seem to have been too much work on this, so I don't know whether it's usable or not.  It would require a bit of rewriting, since right now we just draw the video on top of the existing widgets.  With this, we'd need to position a video widget appropriately.  If we did that, we could use actual GTK widgets for the seek bar, though, so it may be worth the effort.

2) We could add conditional code to do the video rendering via the window system on Mac and Windows.  This would require Mac and/or Windows experts to step up.

3) We could make movie support optional, as @AndreasBilke suggests.  I think the biggest problem here would be getting CMake to do what we want; I don't think there are any gotchas in the code itself.

I'm going to reopen this issue, since I think there are several ways forward.  But there are no promises that I or anyone else will be working on it.

**Comment by maxheld83** [comment]
I unfortunately do not have the expertise to contribute to this myself (just hacking some R and LaTeX), but I'll be happy to keep running `CMake` and posting OS X logs if that's at all helpful.
I really appreciate the great work that you guys have been doing on this project, and I think it could be (much) more widely used, particularly on the (unfortunately? more widespread) OS X platform, where there is no comparable tool available.

(Screw it, or maybe I'll just move to Linux after all :smirk: )

**Comment by AndreasBilke** [comment]
2) would require some vala bindings for conditional rendering on mac os x / windows. If I haven't missed something, vala does not have them (but there exist in the c code).
- is it possible to use directly C code in vala? vala is nothing more than than pre processor magic, but in fact you have C code at the end.

**Comment by rschroll** [comment]
Vala has its own preprocessor.  (I used it in #93.)  We could use that 
along with some CMake magic to put the right rendering code in place 
for each operating system.  We could probably make it detect the system 
it's being run on automatically, although we might want to allow the 
user to override that, if desired.

It is possible to call C from Vala.  Essentially, you need to define a 
function in Vala and annotate it to specify which C function it 
corresponds to.  The vapi files, which provide the GTK, GDK, etc., 
bindings are nothing but a bunch of these annotated function 
definitions.  I've done this before, so I can pull out an example if we 
need it.  I'm not sure we do, though.  I'd hope the other GDK backends 
already have Vala bindings.

I've looked at gtkgst more closely, and it's just drawing the frames 
onto a Gtk.DrawingArea.  We're already using those to display the 
slides, so presumably we could adapt this code to draw frames on only 
part of the DrawingArea.  If anyone feels like trying this out, I can 
try to talk you through the details.  I don't have time to do it myself 
right now, though.

**Comment by AndreasBilke** [comment]
I found http://docs.gstreamer.com/display/GstSDK/Basic+tutorial+5%3A+GUI+toolkit+integration
where they give examples on how to render for mac os x/win 32.

The basic magic is something like this (C-Code):

```
  /* Retrieve window handler from GDK */
#if defined (GDK_WINDOWING_WIN32)
  window_handle = (guintptr)GDK_WINDOW_HWND (window);
#elif defined (GDK_WINDOWING_QUARTZ)
  window_handle = gdk_quartz_window_get_nsview (window);
#elif defined (GDK_WINDOWING_X11)
  window_handle = GDK_WINDOW_XID (window);
#endif
  /* Pass it to playbin2, which implements XOverlay and will forward it to the video sink */
  gst_x_overlay_set_window_handle (GST_X_OVERLAY (data->playbin2), window_handle);
```

They use (depending on the platform) another function call to get the
window handle. The functions for win32/mac os x are not part of the gdk
vapi, so this is the place where C-calls (or own vapi bindings) are needed.

**Comment by AndreasBilke** [comment]
So pdfpc should compile now on OS X, if you disable the movie support. One could create a new issue for movie support on OS X.

**Comment by pat-s** [comment]
Although you state in the `README` that you can turn off the movie support by using `cmake -DMOVIES=OFF`, I suggest to explicitly put a note that this essential if one wants to compile pdfpc on macOS (Sierra here). 

What I found so far is that it is currently not possible to install `gdk-x11-3.0` on macOS [(see here)](http://apple.stackexchange.com/questions/205404/how-can-i-get-gdk-x11-3-0-on-os-x). 

Hence, to make it easier for macOS users to get pdfpc working rather than searching for quite some time regarding this lib problem, just put a small note in your README :)

**Comment by alistairmcmillan** [comment]
@pat-s That was just over a year ago that I wrote that answer on StackExchange. The situation might be different now. :)

**Comment by pat-s** [comment]
Yeah sure. This should just be seen as a friendly suggestion which at least solves the `gdk-x11-3.0` problems atm :) However multiple warnings appear when executing `pdfpc` affecting the normal usage but thats another point.
